[CmdletBinding()]
param(
    [string]$Python = "",
    [string]$Project = ""
)

$ErrorActionPreference = "Stop"
$OutputEncoding = [System.Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = $OutputEncoding
$skillRoot = Split-Path -Parent $PSScriptRoot
if (-not $Python) {
    $venvPython = Join-Path $skillRoot ".venv\Scripts\python.exe"
    $Python = if (Test-Path -LiteralPath $venvPython) { $venvPython } else { "python" }
}
if (-not $Project) { $Project = Join-Path $skillRoot "project.json" }

function Write-Check([string]$Name, [bool]$Passed, [string]$Detail = "") {
    $symbol = if ($Passed) { "[OK]" } else { "[X]" }
    $suffix = if ($Detail) { " - $Detail" } else { "" }
    Write-Output "$symbol $Name$suffix"
}

function Test-PythonImport([string]$Module) {
    & $Python -c "import importlib.util, sys; sys.exit(0 if importlib.util.find_spec('$Module') else 1)" 2>$null
    return $LASTEXITCODE -eq 0
}

Write-Output "MAESA-Agent Doctor"
Write-Output ""

$pythonVersion = ""
try { $pythonVersion = (& $Python --version 2>&1 | Select-Object -First 1).ToString().Trim() } catch {}
$pythonMatch = [regex]::Match($pythonVersion, 'Python\s+(\d+)\.(\d+)')
$pythonOk = $pythonMatch.Success -and [int]$pythonMatch.Groups[1].Value -eq 3 -and [int]$pythonMatch.Groups[2].Value -ge 11
Write-Check "Python 3.11+" $pythonOk $pythonVersion
Write-Check "MCP package" (Test-PythonImport "mcp")
Write-Check "numpy" (Test-PythonImport "numpy")
Write-Check "rasterio" (Test-PythonImport "rasterio")

$registry = Join-Path $skillRoot "interfaces\backend_registry.json"
if (-not (Test-Path -LiteralPath $registry)) { $registry = Join-Path $skillRoot "interfaces\backend_registry.example.json" }
Write-Check "backend registry" (Test-Path -LiteralPath $registry) $registry
$schema = Join-Path $skillRoot "schemas\maesa_project_creation_plan.schema.json"
Write-Check "project schema" (Test-Path -LiteralPath $schema)

Write-Output ""
Write-Output "Software:"
$probe = $null
try {
    $probeJson = & $Python (Join-Path $PSScriptRoot "workflow_agent.py") probe 2>$null
    $probe = $probeJson | Out-String | ConvertFrom-Json
} catch {}
if ($probe -and $probe.software) {
    foreach ($item in @(
        @{ Label = "ArcGIS Pro"; Keys = @("arcgis_pro", "arcgis_propy") },
        @{ Label = "ENVI / IDL"; Keys = @("idl") },
        @{ Label = "PLUS"; Keys = @("plus") },
        @{ Label = "InVEST"; Keys = @("invest") }
    )) {
        $available = $false; $paths = @()
        foreach ($key in $item.Keys) {
            $entry = $probe.software.$key
            if ($entry -and $entry.available) { $available = $true; if ($entry.path) { $paths += $entry.path } }
        }
        Write-Check $item.Label $available ($paths | Select-Object -First 1)
    }
} else {
    foreach ($name in @("ArcGIS Pro", "ENVI / IDL", "PLUS", "InVEST")) { Write-Check $name $false "software probe unavailable" }
}

Write-Output ""
Write-Output "GPU:"
$gpu = $null
try {
    $gpuJson = & $Python -c "import json, importlib.util; torch = __import__('torch') if importlib.util.find_spec('torch') else None; available = bool(torch and torch.cuda.is_available()); print(json.dumps({'available': available, 'name': torch.cuda.get_device_name(0) if available else ''}))" 2>$null
    $gpu = $gpuJson | ConvertFrom-Json
} catch {}
$gpuDetail = if ($gpu -and $gpu.name) { $gpu.name } else { "PyTorch CUDA not available" }
Write-Check "CUDA" ([bool]($gpu -and $gpu.available)) $gpuDetail

Write-Output ""
Write-Output "Data:"
$projectPath = [System.IO.Path]::GetFullPath($Project)
$projectExists = Test-Path -LiteralPath $projectPath
Write-Check "project.json" $projectExists $projectPath
if ($projectExists) {
    try {
        $payload = Get-Content -LiteralPath $projectPath -Raw -Encoding UTF8 | ConvertFrom-Json
        $inputs = $payload.inputs
        $lulcPaths = @($inputs.lulc_baseline) + @($inputs.historical_lulc) + @($inputs.historical_lulc_periods | ForEach-Object { $_.path })
        $hasLulc = @($lulcPaths | Where-Object { $_ -and $_ -notmatch 'replace_' }).Count -gt 0
        $imageryPaths = @($inputs.imagery) + @($inputs.imagery_periods | ForEach-Object { $_.path })
        $hasImagery = @($imageryPaths | Where-Object { $_ -and $_ -notmatch 'replace_' }).Count -gt 0
        $imageryDetail = if ($hasImagery) { "declared in project" } else { "no supplied imagery path" }
        Write-Check "Imagery input" $hasImagery $imageryDetail
        $classificationEnabled = [bool]($payload.classification -and $payload.classification.enabled)
        $lulcReady = $hasLulc -or $classificationEnabled
        $lulcDetail = if ($hasLulc) { "declared in project" } elseif ($classificationEnabled) { "will be generated by classification" } else { "no supplied LULC path" }
        Write-Check "LULC input" $lulcReady $lulcDetail
    } catch {
        Write-Check "LULC input" $false "project.json is not valid JSON"
    }
} else {
    Write-Check "LULC input" $false "project.json is absent"
}

Write-Output ""
Write-Output "Run .\scripts\project_validator.py --project <project.json> before analysis."
